defaults:
    - base_preparator

labels_path_deliminator: __
labels_deliminator: _
image_slices_size_cam1: -1
image_slices_size_cam2: -1
percentage_of_background : 5
reflectance_panel: Null
reflectance_panel_save: null
panel_filter_function: average
merge_images_by_specter: True
match_labels_to_indices: False
