version: '3.4'
name: siapy-app

services:
    siapy-api:
        build:
            context: .
            dockerfile: Dockerfile
        image: siapy-api:latest
        volumes:
            - ./outputs:/app/outputs
            - ./configs:/app/configs
        environment:
            - DISPLAY=${DISPLAY}
