site_name: SiaPy
site_description: A tool for efficient processing of spectral images with Python.
strict: true
site_url: https://github.com/siapy/siapy-lib/tree/main/docs

theme:
  name: "material"
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/lightbulb
        name: "Switch to light mode"
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - navigation.tabs
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.suggest
    - toc.follow
  logo: "images/logo.svg"
  favicon: "favicon.png"

repo_name: siapy/siapy
repo_url: https://github.com/siapy/siapy-lib
edit_uri: edit/main/docs/
extra:
  version:
    provider: mike

nav:
  - Get Started:
      - Welcome to Pydantic: index.md
      - Installation: install.md
      - Contributing: https://github.com/siapy/siapy-lib/blob/main/CONTRIBUTING.md
      - Changelog: https://github.com/siapy/siapy-lib/blob/main/CHANGELOG.md
  - API Documentation:
      - Entity: api/entity.md

markdown_extensions:
  - tables
  - toc:
      permalink: true
      title: Page contents
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.extra
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true

watch:
  - siapy

plugins:
  - mike:
      alias_type: symlink
      canonical_version: latest
  - search
  - exclude:
      glob:
        - __pycache__/*
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          options:
            members_order: source
            separate_signature: true
            filters: ["!^_"]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_signature_annotations: true
            signature_crossrefs: true
            # extensions:
            #   - docs/plugins/griffe_doclinks.py
          import:
            - https://docs.python.org/3/objects.inv
  # - mkdocs-simple-hooks:
  #     hooks:
  #       on_pre_build: "docs.plugins.main:on_pre_build"
  #       on_files: "docs.plugins.main:on_files"
  #       on_page_markdown: "docs.plugins.main:on_page_markdown"
  - external-markdown:
