preparator:
    labels_path_deliminator: str
    labels_deliminator: str
    image_slices_size_cam1: int
    image_slices_size_cam2: int
    percentage_of_background : int
    reflectance_panel: float
    panel_filter_function: str
