data_loader:
    name: data_loader
    data_dir_path: C:\\Users\\janezla\\Documents\\DATA\\ana_slikanje_1-22
    data_sources:
        path_ending_camera1: corr_rad_f32.hdr
        # path_ending_camera2: None
        path_ending_camera2: corr2_rad_f32.hdr
    labels_path_deliminator: __
    labels_deliminator: _
    corregistrate_dir_name: koregistracija
