defaults:
    - base_data_loader

name: data_loader
data_dir_path: /home/janezla/data/project_test
path_ending_camera1: corr_rad_f32.hdr
path_ending_camera2: corr2_rad_f32.hdr
corregistrate_dir_name: koregistracija
labels_of_groups_file_name: labels/groups
