defaults:
    - cameras/camera_nir
    - cameras/camera_swir
    - data_loaders/data_loader
    - custom_config
    - hydra/run/dir
    - override hydra/job_logging: custom_logging
    - _self_

program: ???
