defaults:
    - base/camera
    - base/data_loader
    - base/preparator
    - base/segmentator
    - base/selector
    - base/visualiser
    - custom
    - hydra/run/dir
    - hydra/job/chdir
    - override hydra/job_logging: custom_logging
    - _self_

program: ???
image_idx: 0

