defaults:
    - camera1: camera_nir
    - camera2: camera_swir
    - data_loader: data_loader
    - selector: selector
    - segmentator: segmentator
    - preparator: preparator
    - visualiser: visualiser

name: "project_test"
