defaults:
    - camera1: camera_nir
    - camera2: camera_swir
    - data_loader: data_loader
    - selector: selector
    - segmentator: segmentator
    - preparator: preparator

name: "krompir-ana-1-22"
