name: Publish To PyPI

on:
  # workflow_run:
  #   workflows: [Auto release maker]
  #   types: [completed]
  # pull_request:
  #   branches:
  #     - main
  #   types:
  #     - closed
  push:
    branches: [develop, main]

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@v3
        with:
          version: "head"
      - name: Publish package distributions to PyPI
        run: pdm publish
